# Cargo.toml
[package]
name = "wallet-chain-core"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
swift-bridge-build = "0.1.49"

[dependencies]
swift-bridge = {version = "0.1.49", features = ["async"]}
reqwest = {version = "0.11", features = ["json"]}